import type { Provider, ProviderDetail } from "@/lib/types";

export const mockProviders: Provider[] = [
  {
    id: 1,
    slug: "goaspire-group",
    business_name: "GoAspire Group",
    category: "medical",
    specialty: "Chiropractors",
    city: "Orlando",
    state: "Florida",
    logo_url: "uploads/logos/logo_1752134719196.avif",
    rating: 5,
    review_count: 5,
    is_verified: true,
  },
  {
    id: 2,
    slug: "florida-spine-injury-institute",
    business_name: "Florida Spine & Injury Institute",
    category: "medical",
    specialty: "Chiropractors",
    city: "Winter Haven",
    state: "Florida",
    logo_url: "uploads/logos/logo_1752135108660.png",
    rating: 5,
    review_count: 3,
    is_verified: true,
  },
  {
    id: 3,
    slug: "nunez-law-firm",
    business_name: "Nunez Law Firm",
    category: "legal",
    specialty: "Personal Injury",
    city: "Winter Park",
    state: "Florida",
    logo_url: "uploads/logos/default.jpeg",
    rating: 5,
    review_count: 8,
    is_verified: true,
  },
  {
    id: 4,
    slug: "abercrombie-pa",
    business_name: "Abercrombie PA",
    category: "legal",
    specialty: "Personal Injury",
    city: "Winter Park",
    state: "Florida",
    logo_url: "uploads/logos/default.jpeg",
    rating: 5,
    review_count: 6,
    is_verified: true,
  },
  {
    id: 5,
    slug: "delgo-llc",
    business_name: "Delgo LLC",
    category: "service",
    specialty: "Settlement Services",
    city: "Orlando",
    state: "Florida",
    logo_url: "uploads/logos/default.jpeg",
    rating: 4,
    review_count: 2,
    is_verified: true,
  },
  {
    id: 6,
    slug: "synergy-settlement-services",
    business_name: "Synergy Settlement Services",
    category: "service",
    specialty: "Settlement Services",
    city: "Orlando",
    state: "Florida",
    logo_url: "uploads/logos/default.jpeg",
    rating: 5,
    review_count: 4,
    is_verified: true,
  },
];

export const mockProviderDetail: Record<string, ProviderDetail> = {
  "goaspire-group": {
    id: 1,
    slug: "goaspire-group",
    business_name: "GoAspire Group",
    category: "medical",
    specialty: "Chiropractors",
    city: "Orlando",
    state: "Florida",
    logo_url: "uploads/logos/logo_1752134719196.avif",
    rating: 5,
    review_count: 5,
    is_verified: true,
    description: "GoAspire Group provides comprehensive chiropractic care services in Orlando, Florida.",
    address: "7359 Curry Ford Rd, Orlando, 32822",
    zipcode: "32822",
    phone: "+14079137343",
    website: "https://www.goaspirehealth.com/",
    languages: ["English", "Spanish"],
    services: ["Chiropractors"],
    specialties: [{ id: 1, name: "Chiropractors", category_id: 1 }],
    social_media: {},
    youtube_video_id: "",
    google_maps_url: "",
    gallery: [
      "uploads/logos/logo_1752136847848.jpg",
      "uploads/logos/logo_1752131225703.webp",
      "uploads/logos/logo_1752131783449.png",
      "uploads/logos/logo_1752130537333.jpg",
      "uploads/logos/logo_1752133285339.png",
      "uploads/logos/logo_1752137611442.webp",
      "uploads/logos/logo_1752146803501.png",
    ],
    google_reviews: {
      rating: 5,
      reviews: [
        {
          author: "Rennat Williamson",
          avatar: "https://lh3.googleusercontent.com/a-/ALV-UjXdWNEyRCASpSv6nSq9gAL4b0yCfvw3hG3E-xUOIC3Vy-zG0WAH=s128-c0x00000000-cc-rp-mo",
          rating: 5,
          text: "Great working The Aspire Group! Definitely brought the vision to life!",
        },
        {
          author: "Jennifer Carrau",
          avatar: "https://lh3.googleusercontent.com/a/ACg8ocLiGUZEp24qW4Hc8APDDZtEOB-ySkGOpy8J8cDeHJdSIlWACg=s128-c0x00000000-cc-rp-mo",
          rating: 5,
          text: "Daron and his team are absolutely amazing...great customer service",
        },
        {
          author: "Richard Jones",
          avatar: "https://lh3.googleusercontent.com/a-/ALV-UjWnskWPPIzpReHa1g0WtK8aup0qvVuIrmZQ2cDxrwevp1jm8Ob3=s128-c0x00000000-cc-rp-mo-ba3",
          rating: 5,
          text: "Aspire Group created us a beautiful new website...exceeded our expectations",
        },
        {
          author: "Adam Reynolds",
          avatar: "https://lh3.googleusercontent.com/a/ACg8ocIYcfbpAaBCSTj4_-greNdhVGk8bITwdZrMz3QIY_y2uyPVUw=s128-c0x00000000-cc-rp-mo",
          rating: 5,
          text: "Excellent service from the Aspire Group...Work and design top notch",
        },
        {
          author: "Chris Barney",
          avatar: "https://lh3.googleusercontent.com/a/ACg8ocIugXk6TYZvVob0vpB7HxQeuN3Z3bfLWdWPzA=s128-c0x00000000-cc-rp-mo",
          rating: 5,
          text: "The Aspire Group is absolutely amazing and delivers...driving customers",
        },
      ],
    },
    google_cid: "2608725127066729539",
    related_providers: [],
  },
};
